// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Jk5nJn8YZH1xebG16NgNcL1pqaya2-M',
    appId: '1:958462053305:android:77df3edb411cc4df5b0468',
    messagingSenderId: '958462053305',
    projectId: 'depok-bersih',
    storageBucket: 'depok-bersih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tkPrsB4nWJ2B9cv054UzB16Y5JIrpwU',
    appId: '1:958462053305:ios:3df0c4ddc11ffe685b0468',
    messagingSenderId: '958462053305',
    projectId: 'depok-bersih',
    storageBucket: 'depok-bersih.appspot.com',
    iosClientId: '958462053305-knolj472u53tvfn5fskei90qk60615sm.apps.googleusercontent.com',
    iosBundleId: 'com.muhammadfaiz.depokbersih',
  );
}
